from flask import Blueprint, render_template, request, send_file
from logic import predict_image, allowed_file, UPLOAD_FOLDER
import os, io, json, datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

routes = Blueprint("routes", __name__)

@routes.route("/")
def home():
    return render_template("index.html")

@routes.route("/exit")
def exit():
    return render_template("exit.html")

@routes.route("/about")
def about():
    return render_template("about.html")

@routes.route("/dataset")
def dataset():
    return render_template("dataset.html")

@routes.route("/documents")
def documents():
    docs_folder = os.path.join(os.path.dirname(__file__), 'static', 'docs')
    files = [f for f in os.listdir(docs_folder) if f.lower().endswith(('.pdf', '.png', '.jpg', '.pptx', '.zip'))]
    return render_template("document.html", files=files)

@routes.route("/maps")
def maps():
    return render_template("maps.html")

@routes.route("/", methods=["POST"])
def upload_images():
    predictions = []
    files = request.files.getlist("files")
    valid_files = [f for f in files if f and allowed_file(f.filename)]

    if not valid_files:
        return render_template("index.html", result="No valid image files uploaded.")

    # Clearing previous files
    for f in os.listdir(UPLOAD_FOLDER):
        os.remove(os.path.join(UPLOAD_FOLDER, f))

    tumor_detected = False      # The Tumor flag

    for file in valid_files:
        filepath = os.path.join(UPLOAD_FOLDER, file.filename)
        file.save(filepath)

        result, confidence, all_probs = predict_image(filepath)
        
        predictions.append({
            "filename": file.filename,
            "result": result,
            "confidence": confidence,  
            "all_probs": all_probs
        })

        if result != "\u2705 No signs of brain tumor detected":
            tumor_detected = True
        
    return render_template("index.html", predictions=predictions, tumor_detected=tumor_detected)


@routes.route("/download-report", methods=["POST"])
def download_report():
    predictions = request.form.get("data")
    if not predictions:
        return "No prediction data found", 400

    import json
    import io
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from reportlab.lib.units import inch
    import datetime

    predictions = json.loads(predictions)
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    c.setFont("Times-Roman", 22)
    c.drawCentredString(width / 2, height - 50, "Brain Tumor Detection Report")

    c.setFont("Times-Roman", 12)
    c.drawCentredString(width / 2, height - 70, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    y = height - 110

    for item in predictions:
        if y < 100:
            c.showPage()
            y = height - 50

        result_clean = item["result"].replace("\u26A0\ufe0f", "").replace("\u2705", "").strip()

        c.drawCentredString(width / 2, y, f"Image: {item['filename']}")
        c.drawCentredString(width / 2, y - 15, f"Result: {result_clean}")
        c.drawCentredString(width / 2, y - 30, f"Confidence: {item['confidence']}%")

        # Showing probability breakdown
        if "all_probs" in item:
            prob_str = ", ".join([f"{cls}: {round(conf, 2)}%" for cls, conf in item["all_probs"].items()])
            c.setFont("Times-Roman", 10)
            c.drawCentredString(width / 2, y - 45, f"Probabilities: {prob_str}")
            c.setFont("Times-Roman", 12)
          

      
        y -= 80

    # Footer
    c.setFont("Times-Italic", 10)
    c.drawCentredString(width / 2, 40, "Generated by Brain Tumor Detection System")

    c.save()
    buffer.seek(0)

    return send_file(buffer, as_attachment=True, download_name="tumor_detection_report.pdf", mimetype="application/pdf")


#Dynamic map
from flask import jsonify
import requests
import math

def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat/2)**2 + math.cos(math.radians(lat1)) * \
        math.cos(math.radians(lat2)) * math.sin(dlon/2)**2
    return round(2 * R * math.asin(math.sqrt(a)), 2)

@routes.route("/get_hospitals")
def get_hospitals():
    lat = float(request.args.get("lat"))
    lon = float(request.args.get("lon"))

    query = f"""
    [out:json];
    (
      node["amenity"="hospital"](around:10000,{lat},{lon});
    );
    out;
    """

    response = requests.post(
        "https://overpass-api.de/api/interpreter",
        data=query
    ).json()

    hospitals = []
    for el in response["elements"][:12]:
        if "tags" in el and "name" in el["tags"]:
            hospitals.append({
                "name": el["tags"]["name"],
                "lat": el["lat"],
                "lon": el["lon"],
                "distance": haversine(lat, lon, el["lat"], el["lon"])
            })

    hospitals.sort(key=lambda x: x["distance"])
    return jsonify(hospitals)
